import { describe, expect, test } from 'vitest'
import { readFileSync } from 'fs'
import { resolve } from 'path'
import { parseDu } from './parseDu'

const snapshotHtml = readFileSync(resolve(__dirname, './test.snapshot.html'), { encoding: 'utf-8' })

describe('parseDu()', () => {
  test('result', async () => {
    const result = parseDu(snapshotHtml)
    expect(result).toMatchInlineSnapshot(`
      [
        {
          "artist": "SONIC SURF CITY",
          "cheapestItemPrice": "1,100円(税込)",
          "cheapestItemStatus": "A",
          "genre": "PUNK",
          "itemId": "1006244402",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/1006244402",
          "labelName": "WATERSLIDE RECORDS",
          "productTitle": "LIFE'S A BEACH (2014 REISSUE)",
        },
        {
          "artist": "SONIC SURF CITY",
          "cheapestItemPrice": "1,500円(税込)",
          "cheapestItemStatus": "A",
          "genre": "PUNK",
          "itemId": "1006244411",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/1006244411",
          "labelName": "WATERSLIDE RECORDS",
          "productTitle": "SURF DON'T WALK (2014 REISSUE)",
        },
        {
          "artist": "VA (KING RECORDS)",
          "cheapestItemPrice": "1,700円(税込)",
          "cheapestItemStatus": "A",
          "genre": "PUNK",
          "itemId": "1006308378",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/1006308378",
          "labelName": "キングレコード",
          "productTitle": "I don't like Sex",
        },
        {
          "artist": "EDDIE AND THE HOT RODS エディ・アンド・ザ・ホッド・ロッズ",
          "cheapestItemPrice": "1,700円(税込)",
          "cheapestItemStatus": "B",
          "genre": "PUNK",
          "itemId": "1007603566",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/1007603566",
          "labelName": "LET THEM EAT VINYL",
          "productTitle": "TEENAGE DEPRESSION (LP)",
        },
        {
          "artist": "The Drug Squad",
          "cheapestItemPrice": "380円(税込)",
          "cheapestItemStatus": "B",
          "genre": "PUNK",
          "itemId": "1007736446",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/1007736446",
          "labelName": "PUNK自主商品",
          "productTitle": "Feedback Powder",
        },
        {
          "artist": "CLASH クラッシュ",
          "cheapestItemPrice": "1,550円(税込)",
          "cheapestItemStatus": "A",
          "genre": "PUNK",
          "itemId": "1007967419",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/1007967419",
          "labelName": "ソニー・ミュージック・ジャパン・インターナショナル",
          "productTitle": "LONDON CALLING 40周年記念盤(2CD)",
        },
        {
          "artist": "DOLLY MIXTURE ドリー・ミクスチャー",
          "cheapestItemPrice": "4,850円(税込)",
          "cheapestItemStatus": "S",
          "genre": "ROCK / POPS / INDIE",
          "itemId": "1008019602",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/1008019602",
          "labelName": "SPA GREEN",
          "productTitle": "DEMONSTRATION TAPES (2LP)",
        },
        {
          "artist": "THE CLEANERS",
          "cheapestItemPrice": "480円(税込)",
          "cheapestItemStatus": "A",
          "genre": "PUNK",
          "itemId": "1008182201",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/1008182201",
          "labelName": "POGO77",
          "productTitle": "新東京音楽都市",
        },
        {
          "artist": "HEARTBREAKERS",
          "cheapestItemPrice": "4,850円(税込)",
          "cheapestItemStatus": "S",
          "genre": "PUNK",
          "itemId": "1008274024",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/1008274024",
          "labelName": "JUNGLE",
          "productTitle": "L.A.M.F. - THE FOUND '77 MASTERS (LP)",
        },
        {
          "artist": "COURETTES",
          "cheapestItemPrice": "2,050円(税込)",
          "cheapestItemStatus": "B",
          "genre": "PUNK",
          "itemId": "1008348529",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/1008348529",
          "labelName": "DAMAGED GOODS",
          "productTitle": "HERE ARE THE COURETTES (LP)",
        },
        {
          "artist": "HEARTBREAKERS",
          "cheapestItemPrice": "3,050円(税込)",
          "cheapestItemStatus": "S",
          "genre": "PUNK",
          "itemId": "1008449275",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/1008449275",
          "labelName": "JUNGLE (UK)",
          "productTitle": "L.A.M.F. DEMO SESSIONS (LP/MAGENTA VINYL)",
        },
        {
          "artist": "FOXHOLE(PUNK/JPN)",
          "cheapestItemPrice": "680円(税込)",
          "cheapestItemStatus": "B",
          "genre": "PUNK",
          "itemId": "1008487777",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/1008487777",
          "labelName": "FOXHOLE",
          "productTitle": "Floating song",
        },
        {
          "artist": "JOHNNY THUNDERS & THE HEARTBREAKERS ジョニー・サンダース&ザ・ハートブレイカーズ",
          "cheapestItemPrice": "2,650円(税込)",
          "cheapestItemStatus": "S",
          "genre": "PUNK",
          "itemId": "1008546123",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/1008546123",
          "labelName": "CLEOPATRA",
          "productTitle": "L.A.M.F. LIVE AT THE VILLAGE GATE 1977 (PINK/BLACK SPLATTER
                        VINYL)",
        },
        {
          "artist": "JOHNNY THUNDERS & THE HEARTBREAKERS",
          "cheapestItemPrice": "4,250円(税込)",
          "cheapestItemStatus": "S",
          "genre": "OLD ROCK",
          "itemId": "1008574478",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/1008574478",
          "labelName": undefined,
          "productTitle": "L.A.M.F. THE FOUND '77 MASTERS",
        },
        {
          "artist": "BORED!",
          "cheapestItemPrice": "1,400円(税込)",
          "cheapestItemStatus": "A",
          "genre": "PUNK",
          "itemId": "1008575212",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/1008575212",
          "labelName": "FANTASTIC MESS",
          "productTitle": "FEED THE DOG",
        },
        {
          "artist": "BLONDIE ブロンディ",
          "cheapestItemPrice": "980円(税込)",
          "cheapestItemStatus": "B",
          "genre": "ROCK / POPS / INDIE",
          "itemId": "AWS170508BLO1",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/AWS170508BLO1",
          "labelName": "BMG",
          "productTitle": "POLLINATOR",
        },
        {
          "artist": "BIG AUDIO DYNAMITE II",
          "cheapestItemPrice": "1,700円(税込)",
          "cheapestItemStatus": "B",
          "genre": "PUNK",
          "itemId": "DF171218-079",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/DF171218-079",
          "labelName": "CBS",
          "productTitle": "KOOL-AID",
        },
        {
          "artist": "SEX PISTOLS セックス・ピストルズ",
          "cheapestItemPrice": "680円(税込)",
          "cheapestItemStatus": "B",
          "genre": "PUNK",
          "itemId": "DF171218-200",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/DF171218-200",
          "labelName": undefined,
          "productTitle": "BETTER LIVE THAN DEAD",
        },
        {
          "artist": "DAMNED",
          "cheapestItemPrice": "480円(税込)",
          "cheapestItemStatus": "B",
          "genre": "PUNK",
          "itemId": "DF171222-009",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/DF171222-009",
          "labelName": undefined,
          "productTitle": "DAMNED DAMNED DAMNED",
        },
        {
          "artist": "ONLY ONES オンリーワンズ",
          "cheapestItemPrice": "2,450円(税込)",
          "cheapestItemStatus": "B",
          "genre": "PUNK",
          "itemId": "DF190902-003",
          "itemPageUrl": "https://diskunion.net/used/ct/punk/udetail/DF190902-003",
          "labelName": "ソニー・ミュージック・エンターテイメント",
          "productTitle": "破滅への影",
        },
      ]
    `)
  })
})
