name: 'Clean up: run'

on:
  workflow_dispatch:
  schedule:
    # 毎日 00:00 (15:00 UTC) 実行
    - cron: '0 15 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.0

      - name: Install deps
        run: bun install

      - name: Run delete-old-items
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          DU_SITE_BASE_URL: ${{ secrets.DU_SITE_BASE_URL }}
        run: bun run start:delete-old-items

      - name: Run delete-old-items [DB]
        env:
          DU_SITE_BASE_URL: ${{ secrets.DU_SITE_BASE_URL }}
        run: bun run start:delete-old-items:db

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add data/ pages/
          git commit -m "Cleanup result: $(date "+%Y-%m-%d %H:%M:%S")"
          git push origin main
