name: '[PR] push: lint and test'

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.0

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun run lint

      - name: Run test
        run: bun run test
