name: 'Watcher: run'

on:
  workflow_dispatch:
  schedule:
    # 毎日 12:00 (03:00 UTC) 実行
    - cron: '0 6 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.0

      - name: Install deps
        run: bun install

      - name: Run crawl (with notion)
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          DU_SITE_BASE_URL: ${{ secrets.DU_SITE_BASE_URL }}
        run: bun run start:watcher
