name: 'Watcher: run'

on:
  workflow_dispatch:
  schedule:
    # 毎日 12:00 (03:00 UTC) 実行
    - cron: '0 3 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run crawl
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL }}
          POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_URL }}
        run: pnpm run start:watcher

      # - name: Debug with SSH
      #   if: ${{ always() }}
      #   uses: mxschmitt/action-tmate@v3
