name: 'Watcher: run [DB]'

on:
  workflow_dispatch:
  schedule:
    # 毎日 12:00 (03:00 UTC) 実行
    - cron: '0 3 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.0

      - name: Install deps
        run: bun install

      - name: Run crawl (with DB)
        env:
          DU_SITE_BASE_URL: ${{ secrets.DU_SITE_BASE_URL }}
        run: bun run start:watcher:db

      - name: Build feed
        run: bun run start:build-feed:db
