name: 'Watcher: run [DB]'

on:
  workflow_dispatch:
  schedule:
    # 毎日 12:00 (4:00 UTC) 実行
    - cron: '0 4 * * *'

jobs:
  watch-and-build-feed:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.0

      - name: Install deps
        run: bun install

      - name: Run crawl (with DB)
        env:
          DU_SITE_BASE_URL: ${{ secrets.DU_SITE_BASE_URL }}
        run: bun run start:watcher:db

      - name: Build feed
        run: bun run start:build-feed:db

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add data/ pages/
          git commit -m "Watch result: $(date "+%Y-%m-%d %H:%M:%S")"
          git push origin main

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages/

  deploy:
    runs-on: ubuntu-latest
    needs: watch-and-build-feed
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
